export const coursesData = [
  {
    id: "1",
    title: "Eletricidade",
    category: "Certificação Profissional",
    description:
      "Formação completa em instalações e segurança elétrica com foco em práticas profissionais de mercado.",
    icon: "⚡",
    badge: "Certificação Profissional",
    duration: "3 Meses",
    price: "100.000 Kz",
    instructor: "Maria Silva",
    instructorInfo: {
      name: "Maria Silva",
      title: "Engenheira de Sistemas Elétricos",
      bio: "Mais de 15 anos de experiência em instalações e manutenção de sistemas elétricos. Especialista em normas de segurança ocupacional.",
    },
    modality: "Presencial",
    certification: "Certificado Profissional Incluído",
    startDate: "10 Julho 2026",
    availableSpots: "15 de 20",
    totalSpots: 20,
    enrollmentStatus: "Inscrições Abertas",
    learningPoints: [
      "Circuitos elétricos fundamentais",
      "Segurança e normas de trabalho",
      "Instalação de sistemas elétricos",
      "Manutenção e diagnóstico de falhas",
      "Práticas profissionais avançadas",
    ],
    rating: 4.8,
    reviews: 45,
    hours: 120,
    assignments: 8,
    lastUpdate: "27 Maio 2026",
    imageUrl: "/images/courses/eletricidade.png",
    resources: [
      {
        id: "r1",
        title: "Manual de Segurança Elétrica",
        type: "pdf",
        size: "4.2 MB",
        uploadedDate: "há 2 dias",
      },
      {
        id: "r2",
        title: "Plano de Currículo",
        type: "word",
        size: "1.8 MB",
        uploadedDate: "há 2 dias",
      },
      {
        id: "r3",
        title: "Diapositivos - Módulo 1",
        type: "pdf",
        size: "3.1 MB",
        uploadedDate: "há 5 dias",
      },
      {
        id: "r4",
        title: "Folha de Cálculo de Exercícios",
        type: "excel",
        size: "856 KB",
        uploadedDate: "há 2 dias",
      },
    ],
  },
  {
    id: "2",
    title: "Soldadura Industrial",
    category: "Alta Demanda",
    description:
      "Técnicas avançadas de soldagem para aplicações industriais com hands-on training.",
    icon: "💧",
    badge: "Alta Demanda",
    duration: "3 Meses",
    price: "120.000 Kz",
    instructor: "João Pedro",
    instructorInfo: {
      name: "João Pedro",
      title: "Técnico Certificado em Soldadura",
      bio: "Certificação internacional em soldadura e 20 anos de experiência em projetos industriais de grande escala.",
    },
    modality: "Presencial",
    certification: "Certificado Profissional Incluído",
    startDate: "15 Julho 2026",
    availableSpots: "12 de 20",
    totalSpots: 20,
    enrollmentStatus: "Inscrições Abertas",
    learningPoints: [
      "Técnicas de soldadura industrial",
      "Segurança no ambiente de trabalho",
      "Leitura de desenhos técnicos",
      "Equipamentos de soldagem",
      "Práticas profissionais",
    ],
    rating: 4.9,
    reviews: 52,
    hours: 140,
    assignments: 10,
    lastUpdate: "27 Maio 2026",
    imageUrl: "/images/courses/soldadura.png",
    resources: [
      {
        id: "r1",
        title: "Guia de Técnicas de Soldadura",
        type: "pdf",
        size: "5.4 MB",
        uploadedDate: "há 2 dias",
      },
      {
        id: "r2",
        title: "Especificações Técnicas",
        type: "word",
        size: "2.1 MB",
        uploadedDate: "há 2 dias",
      },
      {
        id: "r3",
        title: "Vídeos Demonstrativos",
        type: "zip",
        size: "215 MB",
        uploadedDate: "há 2 dias",
      },
      {
        id: "r4",
        title: "Checklist de Segurança",
        type: "pdf",
        size: "1.2 MB",
        uploadedDate: "há 5 dias",
      },
    ],
  },
  {
    id: "3",
    title: "Segurança no Trabalho",
    category: "Normas Atualizadas",
    description:
      "Proteção e normas de segurança ocupacional com regulamentações atualizadas.",
    icon: "🛡️",
    badge: "Normas Atualizadas",
    duration: "2 Meses",
    price: "80.000 Kz",
    instructor: "Ana Costa",
    instructorInfo: {
      name: "Ana Costa",
      title: "Especialista em Saúde Ocupacional",
      bio: "Consultora especializada em conformidade e segurança ocupacional com 12 anos de experiência.",
    },
    modality: "Híbrido",
    certification: "Certificado de Conformidade",
    startDate: "20 Julho 2026",
    availableSpots: "18 de 25",
    totalSpots: 25,
    enrollmentStatus: "Inscrições Abertas",
    learningPoints: [
      "Normas de segurança ocupacional",
      "Avaliação de riscos",
      "Equipamentos de proteção individual",
      "Planos de emergência",
      "Conformidade regulatória",
    ],
    rating: 4.7,
    reviews: 38,
    hours: 60,
    assignments: 6,
    lastUpdate: "27 Maio 2026",
    imageUrl: "/images/courses/seguranca.png",
    resources: [
      {
        id: "r1",
        title: "Legislação de Segurança 2026",
        type: "pdf",
        size: "3.8 MB",
        uploadedDate: "há 2 dias",
      },
      {
        id: "r2",
        title: "Matriz de Riscos",
        type: "excel",
        size: "1.5 MB",
        uploadedDate: "há 2 dias",
      },
      {
        id: "r3",
        title: "Templates de Planos",
        type: "word",
        size: "2.3 MB",
        uploadedDate: "há 5 dias",
      },
    ],
  },
  {
    id: "4",
    title: "Mecânica Automotiva",
    category: "Técnica Especializada",
    description:
      "Manutenção e reparação completa de sistemas automotivos modernos.",
    icon: "🔧",
    badge: "Especializada",
    duration: "4 Meses",
    price: "150.000 Kz",
    instructor: "Carlos Mendes",
    instructorInfo: {
      name: "Carlos Mendes",
      title: "Mecânico Certificado - Sistemas Automotivos",
      bio: "Técnico com certificação internacional em diagnóstico automotivo e 18 anos em workshop de ponta.",
    },
    modality: "Presencial",
    certification: "Certificado Técnico",
    startDate: "1 Agosto 2026",
    availableSpots: "8 de 15",
    totalSpots: 15,
    enrollmentStatus: "Inscrições Abertas",
    learningPoints: [
      "Diagnóstico de motores",
      "Sistemas de transmissão",
      "Freios e suspensão",
      "Eletrónica automotiva",
      "Manutenção preventiva",
    ],
    rating: 4.8,
    reviews: 48,
    hours: 160,
    assignments: 12,
    lastUpdate: "27 Maio 2026",
    imageUrl: "/images/courses/mecanica.png",
    resources: [
      {
        id: "r1",
        title: "Manual Técnico Completo",
        type: "pdf",
        size: "8.6 MB",
        uploadedDate: "há 2 dias",
      },
      {
        id: "r2",
        title: "Vídeos de Diagnóstico",
        type: "zip",
        size: "450 MB",
        uploadedDate: "há 2 dias",
      },
      {
        id: "r3",
        title: "Esquemas Elétricos",
        type: "pdf",
        size: "4.2 MB",
        uploadedDate: "há 2 dias",
      },
      {
        id: "r4",
        title: "Tabela de Especificações",
        type: "excel",
        size: "2.1 MB",
        uploadedDate: "há 5 dias",
      },
    ],
  },
  {
    id: "5",
    title: "Programação Web",
    category: "Tecnologia",
    description:
      "Desenvolvimento web moderno com React, Node.js e tecnologias atuais de ponta.",
    icon: "💻",
    badge: "Tecnologia",
    duration: "3 Meses",
    price: "200.000 Kz",
    instructor: "Pedro Oliveira",
    instructorInfo: {
      name: "Pedro Oliveira",
      title: "Desenvolvedor Senior Full Stack",
      bio: "Engenheiro de software com 10 anos em startups e empresas tech. Especialista em React e Node.js.",
    },
    modality: "Online",
    certification: "Certificado de Conclusão",
    startDate: "5 Agosto 2026",
    availableSpots: "20 de 30",
    totalSpots: 30,
    enrollmentStatus: "Inscrições Abertas",
    learningPoints: [
      "HTML, CSS e JavaScript",
      "React e frameworks modernos",
      "Banco de dados",
      "APIs RESTful",
      "Deploy de aplicações",
    ],
    rating: 4.9,
    reviews: 67,
    hours: 120,
    assignments: 8,
    lastUpdate: "27 Maio 2026",
    imageUrl: "/images/courses/programacao.png",
    resources: [
      {
        id: "r1",
        title: "Starter Project",
        type: "zip",
        size: "52 MB",
        uploadedDate: "há 2 dias",
      },
      {
        id: "r2",
        title: "Documentação Completa",
        type: "pdf",
        size: "6.3 MB",
        uploadedDate: "há 2 dias",
      },
      {
        id: "r3",
        title: "Código dos Módulos",
        type: "zip",
        size: "18 MB",
        uploadedDate: "há 2 dias",
      },
      {
        id: "r4",
        title: "Recursos Adicionais",
        type: "word",
        size: "1.9 MB",
        uploadedDate: "há 5 dias",
      },
    ],
  },
  {
    id: "6",
    title: "Contabilidade Básica",
    category: "Gestão",
    description:
      "Fundamentos de contabilidade e gestão financeira para empreendedores.",
    icon: "📊",
    badge: "Gestão",
    duration: "2 Meses",
    price: "90.000 Kz",
    instructor: "Fátima Dias",
    instructorInfo: {
      name: "Fátima Dias",
      title: "Contadora Certificada",
      bio: "Contadora com 14 anos de experiência em gestão financeira para PMEs e consultoria fiscal.",
    },
    modality: "Híbrido",
    certification: "Certificado",
    startDate: "10 Agosto 2026",
    availableSpots: "5 de 20",
    totalSpots: 20,
    enrollmentStatus: "Em Breve",
    learningPoints: [
      "Conceitos contábeis básicos",
      "Escrituração de documentos",
      "Balancetes e balanços",
      "Relatórios financeiros",
      "Conformidade fiscal",
    ],
    rating: 4.6,
    reviews: 31,
    hours: 80,
    assignments: 7,
    lastUpdate: "27 Maio 2026",
    imageUrl: "/images/courses/contabilidade.png",
    resources: [
      {
        id: "r1",
        title: "Plano de Estudos",
        type: "pdf",
        size: "2.7 MB",
        uploadedDate: "há 2 dias",
      },
      {
        id: "r2",
        title: "Exercícios Práticos",
        type: "excel",
        size: "3.2 MB",
        uploadedDate: "há 2 dias",
      },
      {
        id: "r3",
        title: "Templates de Relatórios",
        type: "word",
        size: "1.6 MB",
        uploadedDate: "há 5 dias",
      },
    ],
  },
];
